// Decompiled with JetBrains decompiler
// Type: ExamenDistancia.DatosExamen
// Assembly: ExamenDistancia, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9F2BF469-798D-40E5-B468-6ECB67F0C795
// Assembly location: C:\Users\josue\OneDrive\Desktop\ExamenDistancia_3.exe

using System;

namespace ExamenDistancia
{
  internal class DatosExamen : Configuracion
  {
    public DatosExamen()
    {
      this.NombreMateria = "Programación Orientada a Objetos";
      this.TipoExamen = "Examen práctico ordinario ";
      this.ClaveExamenAsignado = "Ord-examen practico unidad 3 (e) (Distancia)";
      this.TemaExamen = "3.- Polimorfismo, clases abstractas e interfaces";
      this.FechaInicio = new DateTime(2022, 4, 28, 7, 55, 0);
      this.DuracionMinutos = 120;
      this.NombreArchivoConfiguracion = "c:\\apps\\WCYMJT.sys";
      this.BotonAyuda = false;
      this.SitioWebAyuda = "";
      this.ImagenAyuda = false;
      this.Instrucciones = "INSTRUCCIONES, DOCUMENTOS A SUBIR Y PUNTUACIÓN\na) Diagrama de clases (20 puntos)\nb) Diagrama de flujo del método para calcular el importe a pagar y c) Diagrama de flujo del método para comparar (20 puntos)\nd) Codificación.- Subir archivo comprimido sus apellidos en el nombre (60 puntos)\n*** SUBIR LOS DIAGRAMAS EN EL MISMO ARCHIVO *.vsdx de Microsoft Visio con un diagrama en cada página ***\nNúmero de control en el nombre del archivo de Visio. Ejemplos: 20100299.vsdx y LopezTakeyasBruno.zip";
      this.CodificarExamenes();
    }

    public void CodificarExamenes()
    {
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A1)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "6.\u000EQfx%jrgfwf\u007Ffifx%wjlnxywfs%xn%jq%sfhnrnjsyt%ij%xz%gjgî%xjwæ%-t%st.%rjinfsyj%hjxæwjf@%jq%uflt%ij%qf%hjxæwjf%jx%ij%)7815553:51%rnjsywfx%vzj%xn%jx%ufwyt%sfyzwfq%xj%uflfs%)6:15553553%Htrufwj%7%tgojytx%ij%rzojwjx%jrgfwf\u007Ffifx%~%rzjxywj%jq%strgwj%ij%qf%xjötwf%vzj%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A2)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "7.\u000EQtx%ufhnjsyjx%ij%wf~tx%]%nsktwrfs%qf%hfsynifi%ij%uqfhfx%wjvzjwnifx%~%hfif%uqfhf%ij%wf~tx%]%hzjxyf%)::53<:3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ijq%vzj%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A3)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "8.\u000EQtx%ufiwjx%ij%ufhnjsyjx%ij%ujinfywòf%uflfs%)<55%xn%jq%ufhnjsyj%jx%sjtsfyt%t%):55%xn%jx%rf~tw%ij%6%föt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A4)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "9.\u000EQtx%ufhnjsyjx%ij%lfxywtjsyjwtqtlòf%uflfs%)%61:55355%finhntsfqjx%xn%wjvznjwjs%zsf%jsitxhtuòf%t%)%;55%xn%xtqfrjsyj%jx%htsxzqyf%ij%wzynsf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A5)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":.\u000EQtx%ufhnjsyjx%ijsyfqjx%uflfs%)%<55%ujxtx%finhntsfqjx%utw%hfif%unj\u007Ff%ijsyfq%j}ywfòif3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A6)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ";.\u000EQtx%ufhnjsyjx%vzj%htsxzqyfs%js%zwljshnfx%uflfs%)%855%ujxtx%finhntsfqjx%xn%xz%mtwf%ij%fyjshnøs%jx%ijxuzîx%ij%qfx%66?55%UR3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A7)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "<.\u000EQtx%ufhnjsyjx%ij%tkyfqrtqtlòf%uflfs%)%;55%finhntsfqjx%xn%wjvznjwjs%zs%j}frjs%ij%qf%{nxyf%rjinfsyj%htruzyfitwf%t%)%955%finhntsfqjx%xn%xj%ywfyf%ij%zs%j}frjs%twinsfwnt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A8)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "=.\u000EQtx%ufhnjsyjx%hts%fqjwlnfx%uflfs%)%:55%finhntsfqjx%xn%wjvznjwjs%ywfyfrnjsyt%ufwf%ijwrfynynx%~4t%)%855%ufwf%wnsnynx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A9)",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ">.\u000EQtx%ufhnjsyjx%ijq%zwøqtlt%uflfs%)%61<:5%finhntsfqjx%xn%wjvznjwjs%zs%jht%wjsfq%t%xtqt%)%;55%utw%htsxzqyf%ij%wzynsf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A10",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "65.\u000E%Hfif%ufhnjsyj%ij%ywfzrfytqtlòf%uflf%)%8:5%finhntsfqjx%xn%xj%ywfyf%ij%zsf%rzojw%hts%fwywnynx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A11",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "66.\u000E%Qtx%ufhnjsyjx%ij%rjinhnsf%nsyjwsf%uflfs%)<:%finhntsfqjx%utw%hfif%nsyjwuwjyfhnøs%ij%fsæqnxnx%hqòsnhtx%vzj%xtqnhnyjs%fq%rîinht%izwfsyj%xz%htsxzqyf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A12",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "67.\u000E%Qtx%ufhnjsyjx%vzj%htsxzqyfs%js%zwljshnfx%uflfs%)%85%ujxtx%finhntsfqjx%xn%wjvznjwjs%qf%fuqnhfhnøs%ij%ns~jhhntsjx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A13",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "68.\u000E%Qtx%ufhnjsyjx%ij%hfwintqtlòf%uflfs%)79:5%finhntsfqjx%xn%wjvznjwjs%zs%jqjhywthfwintlwfrf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A14",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "69.\u000E%Zs%ufhnjsyj%vzj%wjvznjwj%hnwzlòf%uflf%)%6=55%finhntsfqjx%xn%xj%ywfyf%ij%zsf%hnwzlòf%frgzqfytwnf%t%)%<;55%finhntsfqjx%xn%wjvznjwj%mtxunyfqn\u007Ffhnøs3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A15",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "6:.\u000E%Zs%ufhnjsyj%ijq%szywnøqtlt%uflf%)%6;<:%finhntsfqjx%xn%wjvznjwj%zs%szj{t%jxyzint%ij%szywnhnøs%t%)%87:%utw%htsxzqyf%ij%rtsnytwjt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A16",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "6;.\u000E%Zs%ufhnjsyj%ij%zs%ywfzrfyøqtlt%uflf%)%7<1:55%finhntsfqjx%xn%wjvznjwj%hnwzlòf%ufwf%htqthfwqj%zsf%uwøyjxnx%t%)71<55%xn%xtqfrjsyj%wjvznjwj%nsrt{nqn\u007Ffhnøs%ij%zs%mzjxt%kwfhyzwfit3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A17",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "6<.\u000E%Qtx%ufhnjsyjx%ij%tkyfqrtqtlòf%uflfs%)%7=9:%finhntsfqjx%xn%wjvznjwjs%qjsyjx%szj{t%fwrf\u007Føs%ij%qjsyjx%t%)%:;55%xn%uwjknjwjs%qjsyjx%ij%htsyfhyt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A18",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "6=.\u000E%Qtx%ufiwjx%ij%zs%ufhnjsyj%ijq%ujinfywf%uflfs%)%>55%finhntsfqjx%xn%jq%nskfsyj%wjvznjwj%{fhzsfx%t%xtqt%)9=5%xn%jx%zsf%htsxzqyf%ij%rtsnytwjt%ijq%rjstw3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A19",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "6>.\u000E%Qtx%ufhnjsyjx%ij%sjzrtqtlòf%uflfs%)%<;55%finhntsfqjx%xn%wjvznjwjs%yjwfunf%hts%zs%wjxunwfitw%fwynknhnfq%t%)%;<55%xn%jx%ywfyfrnjsyt%ij%rjinfxynst3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A20",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "75.\u000E%Jq%ufhnjsyj%ij%sjzwtqtlòf%uflf%)%6655%finhntsfqjx%xn%wjvznjwj%zs%fsæqnxnx%ij%jxkzjw\u007Ft%t%)%<;5%xn%xj%ywfyf%ij%rtsnytwjt%ijq%xnxyjrf%sjw{ntxt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%qf%nsyjwkfxj%NHtrufwfgqj%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A21",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "76.\u000EQfx%jrgfwf\u007Ffifx%wjlnxywfs%xn%jq%sfhnrnjsyt%ij%xz%gjgî%xjwæ%-t%st.%rjinfsyj%hjxæwjf@%jq%uflt%ij%qf%hjxæwjf%jx%ij%)7815553:51%rnjsywfx%vzj%xn%jx%ufwyt%sfyzwfq%xj%uflfs%)6:15553553%Htrufwj%7%tgojytx%ij%rzojwjx%jrgfwf\u007Ffifx%~%rzjxywj%jq%strgwj%ij%qf%xjötwf%vzj%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A22",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "77.\u000EQtx%ufhnjsyjx%ij%wf~tx%]%nsktwrfs%qf%hfsynifi%ij%uqfhfx%wjvzjwnifx%~%hfif%uqfhf%ij%wf~tx%]%hzjxyf%)::53<:3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ijq%vzj%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A23",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "78.\u000EQtx%ufiwjx%ij%ufhnjsyjx%ij%ujinfywòf%uflfs%)<55%xn%jq%ufhnjsyj%jx%sjtsfyt%t%):55%xn%jx%rf~tw%ij%6%föt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A24",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "79.\u000EQtx%ufhnjsyjx%ij%lfxywtjsyjwtqtlòf%uflfs%)%61:55355%finhntsfqjx%xn%wjvznjwjs%zsf%jsitxhtuòf%t%)%;55%xn%xtqfrjsyj%jx%htsxzqyf%ij%wzynsf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A25",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "7:.\u000EQtx%ufhnjsyjx%ijsyfqjx%uflfs%)%<55%ujxtx%finhntsfqjx%utw%hfif%unj\u007Ff%ijsyfq%j}ywfòif3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A26",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "7;.\u000EQtx%ufhnjsyjx%vzj%htsxzqyfs%js%zwljshnfx%uflfs%)%855%ujxtx%finhntsfqjx%xn%xz%mtwf%ij%fyjshnøs%jx%ijxuzîx%ij%qfx%66?55%UR3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A27",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "7<.\u000EQtx%ufhnjsyjx%ij%tkyfqrtqtlòf%uflfs%)%;55%finhntsfqjx%xn%wjvznjwjs%zs%j}frjs%ij%qf%{nxyf%rjinfsyj%htruzyfitwf%t%)%955%finhntsfqjx%xn%xj%ywfyf%ij%zs%j}frjs%twinsfwnt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A28",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "7=.\u000EQtx%ufhnjsyjx%hts%fqjwlnfx%uflfs%)%:55%finhntsfqjx%xn%wjvznjwjs%ywfyfrnjsyt%ufwf%ijwrfynynx%~4t%)%855%ufwf%wnsnynx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A29",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "7>.\u000EQtx%ufhnjsyjx%ijq%zwøqtlt%uflfs%)%61<:5%finhntsfqjx%xn%wjvznjwjs%zs%jht%wjsfq%t%xtqt%)%;55%utw%htsxzqyf%ij%wzynsf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A30",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "85.\u000E%Hfif%ufhnjsyj%ij%ywfzrfytqtlòf%ufwf%)%8:5%finhntsfqjx%xn%xj%ywfyf%ij%zsf%rzojw%hts%fwywnynx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A31",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "86.\u000E%Qtx%ufhnjsyjx%ij%rjinhnsf%nsyjwsf%uflfs%)<:%finhntsfqjx%utw%hfif%nsyjwuwjyfhnøs%ij%fsæqnxnx%hqòsnhtx%vzj%xtqnhnyjs%fq%rîinht%izwfsyj%xz%htsxzqyf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A32",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "87.\u000E%Qtx%ufhnjsyjx%vzj%htsxzqyfs%js%zwljshnfx%uflfs%)%85%ujxtx%finhntsfqjx%xn%wjvznjwjs%qf%fuqnhfhnøs%ij%ns~jhhntsjx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A33",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "88.\u000E%Qtx%ufhnjsyjx%ij%hfwintqtlòf%uflfs%)79:5%finhntsfqjx%xn%wjvznjwjs%zs%jqjhywthfwintlwfrf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A34",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "89.\u000E%Zs%ufhnjsyj%vzj%wjvznjwj%hnwzlòf%uflf%)%6=55%finhntsfqjx%xn%xj%ywfyf%ij%zsf%hnwzlòf%frgzqfytwnf%t%)%<;55%finhntsfqjx%xn%wjvznjwj%mtxunyfqn\u007Ffhnøs3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A35",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "8:.\u000E%Zs%ufhnjsyj%ijq%szywnøqtlt%uflf%)%6;<:%finhntsfqjx%xn%wjvznjwj%zs%szj{t%jxyzint%ij%szywnhnøs%t%)%87:%utw%htsxzqyf%ij%rtsnytwjt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A36",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "8;.\u000E%Zs%ufhnjsyj%ij%zs%ywfzrfyøqtlt%uflf%)%7<1:55%finhntsfqjx%xn%wjvznjwj%hnwzlòf%ufwf%htqthfwqj%zsf%uwøyjxnx%t%)71<55%xn%xtqfrjsyj%wjvznjwj%nsrt{nqn\u007Ffhnøs%ij%zs%mzjxt%kwfhyzwfit3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A37",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "8<.\u000E%Qtx%ufhnjsyjx%ij%tkyfqrtqtlòf%uflfs%)%7=9:%finhntsfqjx%xn%wjvznjwjs%qjsyjx%szj{t%fwrf\u007Føs%ij%qjsyjx%t%)%:;55%xn%uwjknjwjs%qjsyjx%ij%htsyfhyt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A38",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "8=.\u000E%Qtx%ufiwjx%ij%zs%ufhnjsyj%ijq%ujinfywf%uflfs%)%>55%finhntsfqjx%xn%jq%nskfsyj%wjvznjwj%{fhzsfx%t%xtqt%)9=5%xn%jx%zsf%htsxzqyf%ij%rtsnytwjt%ijq%rjstw3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A39",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "8>.\u000E%Qtx%ufhnjsyjx%ij%sjzrtqtlòf%uflfs%)%<;55%finhntsfqjx%xn%wjvznjwjs%yjwfunf%hts%zs%wjxunwfitw%fwynknhnfq%t%)%;<55%xn%jx%ywfyfrnjsyt%ij%rjinfxynst3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A40",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "95.\u000E%Jq%ufhnjsyj%ij%sjzwtqtlòf%uflf%)%6655%finhntsfqjx%xn%wjvznjwj%zs%fsæqnxnx%ij%jxkzjw\u007Ft%t%)%<;5%xn%xj%ywfyf%ij%rtsnytwjt%ijq%xnxyjrf%sjw{ntxt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%nsyjwkfxj%~%zs%rîytit%inxjöfitx%utw%jq%uwtlwfrfitw%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A41",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "96.\u000EQfx%jrgfwf\u007Ffifx%wjlnxywfs%xn%jq%sfhnrnjsyt%ij%xz%gjgî%xjwæ%-t%st.%rjinfsyj%hjxæwjf@%jq%uflt%ij%qf%hjxæwjf%jx%ij%)7815553:51%rnjsywfx%vzj%xn%jx%ufwyt%sfyzwfq%xj%uflfs%)6:15553553%Htrufwj%7%tgojytx%ij%rzojwjx%jrgfwf\u007Ffifx%~%rzjxywj%jq%strgwj%ij%qf%xjötwf%vzj%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A42",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "97.\u000EQtx%ufhnjsyjx%ij%wf~tx%]%nsktwrfs%qf%hfsynifi%ij%uqfhfx%wjvzjwnifx%~%hfif%uqfhf%ij%wf~tx%]%hzjxyf%)::53<:3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ijq%vzj%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A43",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "98.\u000EQtx%ufiwjx%ij%ufhnjsyjx%ij%ujinfywòf%uflfs%)<55%xn%jq%ufhnjsyj%jx%sjtsfyt%t%):55%xn%jx%rf~tw%ij%6%föt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A44",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "99.\u000EQtx%ufhnjsyjx%ij%lfxywtjsyjwtqtlòf%uflfs%)%61:55355%finhntsfqjx%xn%wjvznjwjs%zsf%jsitxhtuòf%t%)%;55%xn%xtqfrjsyj%jx%htsxzqyf%ij%wzynsf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A45",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "9:.\u000EQtx%ufhnjsyjx%ijsyfqjx%uflfs%)%<55%ujxtx%finhntsfqjx%utw%hfif%unj\u007Ff%ijsyfq%j}ywfòif3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A46",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "9;.\u000EQtx%ufhnjsyjx%vzj%htsxzqyfs%js%zwljshnfx%uflfs%)%855%ujxtx%finhntsfqjx%xn%xz%mtwf%ij%fyjshnøs%jx%ijxuzîx%ij%qfx%66?55%UR3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A47",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "9<.\u000EQtx%ufhnjsyjx%ij%tkyfqrtqtlòf%uflfs%)%;55%finhntsfqjx%xn%wjvznjwjs%zs%j}frjs%ij%qf%{nxyf%rjinfsyj%htruzyfitwf%t%)%955%finhntsfqjx%xn%xj%ywfyf%ij%zs%j}frjs%twinsfwnt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A48",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "9=.\u000EQtx%ufhnjsyjx%hts%fqjwlnfx%uflfs%)%:55%finhntsfqjx%xn%wjvznjwjs%ywfyfrnjsyt%ufwf%ijwrfynynx%~4t%)%855%ufwf%wnsnynx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A49",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "9>.\u000EQtx%ufhnjsyjx%ijq%zwøqtlt%uflfs%)%61<:5%finhntsfqjx%xn%wjvznjwjs%zs%jht%wjsfq%t%xtqt%)%;55%utw%htsxzqyf%ij%wzynsf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A50",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":5.\u000E%Hfif%ufhnjsyj%ij%ywfzrfytqtlòf%ufwf%)%8:5%finhntsfqjx%xn%xj%ywfyf%ij%zsf%rzojw%hts%fwywnynx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A51",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":6.\u000E%Qtx%ufhnjsyjx%ij%rjinhnsf%nsyjwsf%uflfs%)<:%finhntsfqjx%utw%hfif%nsyjwuwjyfhnøs%ij%fsæqnxnx%hqòsnhtx%vzj%xtqnhnyjs%fq%rîinht%izwfsyj%xz%htsxzqyf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A52",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":7.\u000E%Qtx%ufhnjsyjx%vzj%htsxzqyfs%js%zwljshnfx%uflfs%)%85%ujxtx%finhntsfqjx%xn%wjvznjwjs%qf%fuqnhfhnøs%ij%ns~jhhntsjx3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A53",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":8.\u000E%Qtx%ufhnjsyjx%ij%hfwintqtlòf%uflfs%)79:5%finhntsfqjx%xn%wjvznjwjs%zs%jqjhywthfwintlwfrf3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A54",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":9.\u000E%Zs%ufhnjsyj%vzj%wjvznjwj%hnwzlòf%uflf%)%6=55%finhntsfqjx%xn%xj%ywfyf%ij%zsf%hnwzlòf%frgzqfytwnf%t%)%<;55%finhntsfqjx%xn%wjvznjwj%mtxunyfqn\u007Ffhnøs3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A55",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = "::.\u000E%Zs%ufhnjsyj%ijq%szywnøqtlt%uflf%)%6;<:%finhntsfqjx%xn%wjvznjwj%zs%szj{t%jxyzint%ij%szywnhnøs%t%)%87:%utw%htsxzqyf%ij%rtsnytwjt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A56",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":;.\u000E%Zs%ufhnjsyj%ij%zs%ywfzrfyøqtlt%uflf%)%7<1:55%finhntsfqjx%xn%wjvznjwj%hnwzlòf%ufwf%htqthfwqj%zsf%uwøyjxnx%t%)71<55%xn%xtqfrjsyj%wjvznjwj%nsrt{nqn\u007Ffhnøs%ij%zs%mzjxt%kwfhyzwfit3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A57",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":<.\u000E%Qtx%ufhnjsyjx%ij%tkyfqrtqtlòf%uflfs%)%7=9:%finhntsfqjx%xn%wjvznjwjs%qjsyjx%szj{t%fwrf\u007Føs%ij%qjsyjx%t%)%:;55%xn%uwjknjwjs%qjsyjx%ij%htsyfhyt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A58",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":=.\u000E%Qtx%ufiwjx%ij%zs%ufhnjsyj%ijq%ujinfywf%uflfs%)%>55%finhntsfqjx%xn%jq%nskfsyj%wjvznjwj%{fhzsfx%t%xtqt%)9=5%xn%jx%zsf%htsxzqyf%ij%rtsnytwjt%ijq%rjstw3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A59",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ":>.\u000E%Qtx%ufhnjsyjx%ij%sjzrtqtlòf%uflfs%)%<;55%finhntsfqjx%xn%wjvznjwjs%yjwfunf%hts%zs%wjxunwfitw%fwynknhnfq%t%)%;<55%xn%jx%ywfyfrnjsyt%ij%rjinfxynst3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%ræx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
      this.miListaExamenes.Add(new Examen()
      {
        Clave = "A60",
        Redaccion = "F32%Qtx%ufhnjsyjx%ij%zsf%hqòsnhf%xj%hqfxnknhfs%ij%fhzjwit%fq%ynut%ij%ywfyfrnjsyt%xtqnhnyfit3%Ytitx%qtx%ufhnjsyjx%ynjsjs%qtx%xnlznjsyjx%ifytx?\u000F/%Strgwj\u000F/%Xj}t\u000F/%Jifi\u000F/%Htxyt%ij%htsxzqyf%ljsjwfq\u000F/%Rîytit%HfqhzqfwUflt-%.%vzj%ij{zjq{j%jq%nrutwyj%f%uflfw%utw%qf%htsxzqyf\u000FYtitx%qtx%ufhnjsyjx%uflfs%jq%htxyt%ij%qf%htsxzqyf%ljsjwfq%0%jq%htxyt%ij%xz%ywfyfrnjsyt%ufwynhzqfw3%Inxjöj%zsf%fuqnhfhnøs%utqnrøwknhf%hts%zsf%hqfxj%gfxj%fgxywfhyf%hts%qtx%ifytx%ljsjwfqjx%htrzsjx%ij%qtx%ufhnjsyjx1%zs%rîytit%fgxywfhyt%HfqhzqfwUflt-%.%vzj%ijgj%xtgwjxhwngnwxj%js%qf%hqfxj%ijwn{fif%ufwf%ij{tq{jw%jq%nrutwyj%f%uflfw%utw%jq%ufhnjsyj%htsxnijwfsit%qf%xnlznjsyj%xnyzfhnøs%rîinhf%-flwjlzj%f%qf%hqfxj%ijwn{fif%qt%sjhjxfwnt%ufwf%wjxtq{jw%qf%xnyzfhnøs%xtqnhnyfif.?\u000F\u000F-XTQFRJSYJ%MFLF%QTX%INFLWFRFX%IJ%HQFXJX%^%IJ%KQZOT%IJQ%UFHNJSYJ%VZJ%XJ%RJSHNTSF%JS%XZ%JOJWHNHNT1%ST%JX%SJHJXFWNT%VZJ%QT%WJFQNHJ%UFWF%YTITX%QTX%YNUTX%IJ%UFHNJSYJX.\u000F",
        Inciso = ";5.\u000E%Jq%ufhnjsyj%ij%sjzwtqtlòf%uflf%)%6655%finhntsfqjx%xn%wjvznjwj%zs%fsæqnxnx%ij%jxkzjw\u007Ft%t%)%<;5%xn%xj%ywfyf%ij%rtsnytwjt%ijq%xnxyjrf%sjw{ntxt3%Htrufwj%7%tgojytx%ij%ufhnjsyjx%~%rzjxywj%jq%strgwj%ij%vznjs%uflfwæ%rjstx3%Zynqnhj%zsf%qf%xtgwjxhwnyzwf%ij%zs%rîytit%fgxywfhyt%mjwjifit%ij%qf%hqfxj%gfxj%fgxywfhyf%ufwf%mfhjw%qf%htrufwfhnøs3"
      });
    }
  }
}
